// Generated Convex API
// This file is auto-generated by Convex and should not be edited manually

export const api = {
  // Placeholder API object for development
  // In a real Convex setup, this would be auto-generated
  users: {
    list: "users:list",
    get: "users:get",
    create: "users:create",
    update: "users:update",
    delete: "users:delete",
  },
  workOrders: {
    list: "workOrders:list",
    get: "workOrders:get",
    create: "workOrders:create",
    update: "workOrders:update",
    delete: "workOrders:delete",
  },
  providers: {
    list: "providers:list",
    get: "providers:get",
    create: "providers:create",
    update: "providers:update",
    delete: "providers:delete",
  },
  activities: {
    list: "activities:list",
    get: "activities:get",
    create: "activities:create",
    update: "activities:update",
    delete: "activities:delete",
  },
  progress: {
    list: "progress:list",
    get: "progress:get",
    create: "progress:create",
    update: "progress:update",
    delete: "progress:delete",
  },
} as const

export default api
